title: 'Trainer-Led Learning'
template: trainer_led_learning/show
layout: layout
taxonomies:
  - staff_groups
revisions: false
route: '/trainer-led-learning/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
